server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8081  # Address of user-service
          predicates:
            - Path=/users/**          # Routes starting with /users
        - id: order-service
          uri: http://localhost:8082  # Address of order-service
          predicates:
            - Path=/orders/**         # Routes starting with /orders
      discovery:
        locator:
          enabled: true  # Enables discovery-based routing
          lower-case-service-id: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/